#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

# Load HEAD of master branch until we tag an intial release
cookbook 'drupal',
  :git => 'git://github.com/xforty/chef-drupal.git',
  :ref => 'master'

# Load HEAD of master branch until development calms down
cookbook 'drush',
  :git => 'git://github.com/xforty/chef-drush.git',
  :ref => 'master'

# Load HEAD of master branch until we tag an intial release
cookbook 'initdb',
  :git => 'git://github.com/xforty/chef-initdb.git',
  :ref => 'master'

# Load from xforty repo until known issue is fixed
# http://tickets.opscode.com/browse/COOK-932
cookbook 'mysql',
  :git => 'git://github.com/xforty/chef-mysql.git',
  :ref => 'xforty'

# Load HEAD of master branch until we tag an intial release
cookbook 'php_module',
  :git => 'git://github.com/xforty/chef-php_module.git',
  :ref => 'master'

# Load HEAD of master branch until we tag an intial release
cookbook 'php_pear',
  :git => 'git://github.com/xforty/chef-php_pear.git',
  :ref => 'master'

cookbook 'rpmforge',
  :git => 'git://github.com/xforty/chef-rpmforge.git',
  :ref => '0.0.1'

# Load HEAD of master branch until we tag an intial release
cookbook 'squid',
  :git => 'git://github.com/xforty/chef-squid.git',
  :ref => 'master'

# Load HEAD of master branch until we tag an intial release
cookbook 'xforty',
  :git => 'git://github.com/xforty/chef-xforty.git',
  :ref => 'master'
