#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

# Load HEAD of master branch until we tag an intial release
cookbook 'drupal',
  :git => 'git://github.com/xforty/chef-drupal.git',
  :ref => 'master'

# Load HEAD of master branch until development calms down
cookbook 'drush',
  :git => 'git://github.com/xforty/chef-drush.git',
  :ref => 'master'

# Load HEAD of master branch until we tag an intial release
cookbook 'initdb',
  :git => 'git://github.com/xforty/chef-initdb.git',
  :ref => 'master'

# Load from xforty repo until known issue is fixed
# https://github.com/opscode/cookbooks/pull/286
cookbook 'mysql',
  :git => 'git://github.com/xforty/cookbooks.git',
  :ref => 'xforty',
  :path => 'mysql'

# Load HEAD of master branch until we tag an intial release
cookbook 'pear',
  :git => 'git://github.com/xforty/chef-pear.git',
  :ref => 'master'

# Load from xforty repo until known issue is fixed
# http://tickets.opscode.com/browse/COOK-993
cookbook 'php',
  :git => 'git://github.com/xforty/cookbooks.git',
  :ref => 'xforty',
  :path => 'php'

cookbook 'php_curl',
  :git => 'git://github.com/xforty/chef-php_curl.git',
  :ref => '0.0.1'

cookbook 'php_gd',
  :git => 'git://github.com/xforty/chef-php_gd.git',
  :ref => '0.0.1'

cookbook 'php_mysql',
  :git => 'git://github.com/xforty/chef-php_mysql.git',
  :ref => '0.0.1'

cookbook 'php_xml',
  :git => 'git://github.com/xforty/chef-php_xml.git',
  :ref => '0.0.1'

cookbook 'rpmforge',
  :git => 'git://github.com/xforty/chef-rpmforge.git',
  :ref => '0.0.1'

# Load HEAD of master branch until we tag an intial release
cookbook 'xforty',
  :git => 'git://github.com/xforty/chef-xforty.git',
  :ref => 'master'
